image:
  file: .gitpod.Dockerfile

#tasks:
#  - init: 'echo "TODO: Replace with init/build command"'
#    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==